export interface User{
    uiNum?:number;
    uiId?:string;
    uiPwd?:string;
    uiName?:string;
    uiEmail?:string;
    uiMobile?:string;
    uiZonecode?:string;
    uiRoadaddr?:string;
    uiDetailAddr?:string;
    uiRole?:string;
    credat?:string;
    lmodat?:string;
    active?:string;
    uiDesc?:string;
    uiImgName?:string;
    uiImgPath?:string;
    file?:string;
    token?:string;
    riRank?:number;
    riComment?:Array<Array<string>>;
    login?:string;
    loginDate?:string;
}